"""Intravital imaging — in vivo cell tracking, z-stacks, vessel dynamics, shape + homing + events."""

from ...core.contract import register_modality
from ._aesthetic import AESTHETIC

register_modality(
    name="intravital_imaging",
    description=(
        "Cell-track trajectories, depth-coded microglia fields, "
        "two-photon MIPs, vessel-diameter kymographs, cell-shape "
        "descriptor violins, migration rose diagrams, time-to-homing "
        "survival, per-cell event rasters, territory-change pre/post "
        "polygons, surveillance-efficiency forests, pairwise cell-cell "
        "contact matrices, laser-injury radial responses, multi-channel "
        "RGB overlays, ensemble MSD curves with α-slopes, instantaneous-"
        "speed split violins."
    ),
    aesthetic=AESTHETIC,
)

from . import (  # noqa: E402,F401
    aligned_vs_unaligned_velocity_split,
    biosensor_activation_field_per_cell,
    biosensor_dose_response_curve,
    branch_order_topology_per_cell,
    cell_cell_contact_frequency_matrix,
    cell_shape_descriptors_by_state,
    cell_track_trajectory_field,
    chemotaxis_index_trajectory,
    cohort_baseline_balance_table_matrix,
    commitment_hazard_with_age,
    commitment_phase_diagram,
    commitment_vs_chemotaxis_contingency,
    cue_response_dose_latency,
    cue_to_net_displacement_latency,
    cue_to_reorientation_latency,
    curvature_along_protrusion_kymograph,
    depth_projected_microglia_field,
    directional_persistence_autocorr,
    dose_x_time_response_matrix,
    dwell_time_distribution_per_state,
    emission_distribution_per_state,
    equivalence_tost_radar_per_condition,
    hazard_rate_per_state,
    hmm_vs_hsmm_model_comparison,
    kinematic_power_spectral_density,
    laser_injury_response_radial,
    latency_decomposition_forest,
    launch_to_commitment_latency,
    migration_rose_diagram,
    model_calibration_brier_forest,
    msd_curve_by_state,
    multi_channel_intravital_overlay,
    ornstein_uhlenbeck_fit_per_state,
    photobleaching_corrected_intensity_traces,
    posterior_state_probability_ribbons,
    process_event_timeline,
    protrusion_commitment_survival,
    protrusion_dominance_race_winner,
    sojourn_survival_per_state,
    speed_commitment_coupling,
    state_conditional_tip_msd,
    state_decoded_protrusion_polyline_field,
    state_decoded_tip_track_field,
    state_entry_exit_raster,
    state_kinematic_spectral_embedding,
    state_occupancy_stacked_area,
    state_transition_kernel_matrix,
    surveillance_efficiency_metric,
    territory_change_pre_post,
    time_to_homing_survival,
    tip_pair_correlation_in_window,
    tip_ripleys_k_in_window,
    transfer_entropy_state_to_velocity_matrix,
    two_photon_depth_projection,
    velocity_distribution_by_state,
    vessel_diameter_kymograph,
    viscous_drag_tip_force_map,
)

__all__ = [
    "AESTHETIC",
    "aligned_vs_unaligned_velocity_split",
    "biosensor_activation_field_per_cell",
    "biosensor_dose_response_curve",
    "branch_order_topology_per_cell",
    "cell_cell_contact_frequency_matrix",
    "cell_shape_descriptors_by_state",
    "cell_track_trajectory_field",
    "chemotaxis_index_trajectory",
    "cohort_baseline_balance_table_matrix",
    "commitment_hazard_with_age",
    "commitment_phase_diagram",
    "commitment_vs_chemotaxis_contingency",
    "cue_response_dose_latency",
    "cue_to_net_displacement_latency",
    "cue_to_reorientation_latency",
    "curvature_along_protrusion_kymograph",
    "depth_projected_microglia_field",
    "directional_persistence_autocorr",
    "dose_x_time_response_matrix",
    "dwell_time_distribution_per_state",
    "emission_distribution_per_state",
    "equivalence_tost_radar_per_condition",
    "hazard_rate_per_state",
    "hmm_vs_hsmm_model_comparison",
    "kinematic_power_spectral_density",
    "laser_injury_response_radial",
    "latency_decomposition_forest",
    "launch_to_commitment_latency",
    "migration_rose_diagram",
    "model_calibration_brier_forest",
    "msd_curve_by_state",
    "multi_channel_intravital_overlay",
    "ornstein_uhlenbeck_fit_per_state",
    "photobleaching_corrected_intensity_traces",
    "posterior_state_probability_ribbons",
    "process_event_timeline",
    "protrusion_commitment_survival",
    "protrusion_dominance_race_winner",
    "sojourn_survival_per_state",
    "speed_commitment_coupling",
    "state_conditional_tip_msd",
    "state_decoded_protrusion_polyline_field",
    "state_decoded_tip_track_field",
    "state_entry_exit_raster",
    "state_kinematic_spectral_embedding",
    "state_occupancy_stacked_area",
    "state_transition_kernel_matrix",
    "surveillance_efficiency_metric",
    "territory_change_pre_post",
    "time_to_homing_survival",
    "tip_pair_correlation_in_window",
    "tip_ripleys_k_in_window",
    "transfer_entropy_state_to_velocity_matrix",
    "two_photon_depth_projection",
    "velocity_distribution_by_state",
    "vessel_diameter_kymograph",
    "viscous_drag_tip_force_map",
]
