"""Manifest schema, resolver, and catalog generator."""

from .auto_tag import auto_tag_all, auto_tag_recipe
from .catalog import (
    INDEX_SCHEMA_VERSION,
    build_catalog,
    build_index,
    catalog_fingerprint,
    emit_index_json,
    write_catalog_json,
)
from .data_bridge import (
    DataFile,
    FieldBinding,
    RecipeBinding,
    bind_recipe_to_data,
    bind_shortlist_to_data,
    compute_fully_bound,
    discover_data_files,
    load_bindings_cache,
    to_render_binding,
    to_render_data_files,
    write_bindings_cache,
)
from .figure_composition import (
    compose_figure,
    render_figure_yaml,
    validate_figure_yaml,
)
from .figure_schema import (
    FigureSpec as FigureCompositionSpec,
)
from .figure_schema import (
    FreeformLayout,
    GridLayout,
    GridspecLayout,
    PartitionedPanelSpec,
)
from .figure_schema import (
    PanelSpec as CompositionPanelSpec,
)
from .intake import (
    INTAKE_QUESTIONS,
    IntakeAnswer,
    IntakeQuestion,
    intake_questions_for_index,
    run_intake_interactive,
)
from .project_scan import (
    InferredAnswer,
    ProjectScanResult,
    scan_project,
    to_intake_pre_filled,
)
from .provenance import (
    PROVENANCE_SCHEMA_VERSION,
    ProvenanceRecord,
    VerificationResult,
    build_provenance,
    bundle_provenance,
    diff_provenance,
    load_provenance_json,
    verify_provenance,
    write_provenance_json,
)
from .render_loop import (
    EnvironmentalFailure,
    RenderBinding,
    RenderDataFile,
    RenderLog,
    RenderOutcome,
    render_shortlist,
    write_render_report,
)
from .resolver import render_manifest, resolve_panel_data, validate_manifest
from .schema import FigureSpec, Manifest, PanelSpec, load_manifest
from .scoring import (
    DEFAULT_SHORTLIST_SIZE,
    MINIMUM_SCORE_FOR_SHORTLIST,
    SCORING_RUBRIC_VERSION,
    WEIGHTS,
    ProjectProfile,
    ScoredRecipe,
    score_recipes,
    scoring_rubric_dict,
)
from .statistical_audit import (
    ALL_RULE_NAMES,
    AuditFinding,
    AuditReport,
    StatisticalContractViolation,
    audit_recipe_against_data,
)
from .tag_taxonomy import (
    BOOL_TAGS,
    TAG_ENUMS,
    UNKNOWN_SENTINEL,
    TagAnchor,
    TagDimensionality,
    TagDynamics,
    TagValidationError,
    TagWave,
    validate_tag,
    validate_tag_dict,
)
from .vision_input import (
    RefinementOutcome,
    VisionInference,
    VisionScanResult,
    VisionUnavailableError,
    refine_figure,
    vision_scan_reference_figure,
)
from .vision_input import (
    to_intake_pre_filled as to_intake_pre_filled_from_vision,
)

__all__ = [
    "ALL_RULE_NAMES",
    "AuditFinding",
    "AuditReport",
    "BOOL_TAGS",
    "CompositionPanelSpec",
    "DEFAULT_SHORTLIST_SIZE",
    "DataFile",
    "EnvironmentalFailure",
    "FieldBinding",
    "FigureCompositionSpec",
    "FigureSpec",
    "FreeformLayout",
    "GridLayout",
    "GridspecLayout",
    "INDEX_SCHEMA_VERSION",
    "INTAKE_QUESTIONS",
    "InferredAnswer",
    "IntakeAnswer",
    "IntakeQuestion",
    "MINIMUM_SCORE_FOR_SHORTLIST",
    "Manifest",
    "PROVENANCE_SCHEMA_VERSION",
    "PanelSpec",
    "PartitionedPanelSpec",
    "ProjectProfile",
    "ProjectScanResult",
    "ProvenanceRecord",
    "RecipeBinding",
    "RenderBinding",
    "RenderDataFile",
    "RenderLog",
    "RenderOutcome",
    "SCORING_RUBRIC_VERSION",
    "ScoredRecipe",
    "StatisticalContractViolation",
    "TAG_ENUMS",
    "TagAnchor",
    "TagDimensionality",
    "TagDynamics",
    "TagValidationError",
    "TagWave",
    "UNKNOWN_SENTINEL",
    "RefinementOutcome",
    "VerificationResult",
    "VisionInference",
    "VisionScanResult",
    "VisionUnavailableError",
    "WEIGHTS",
    "audit_recipe_against_data",
    "auto_tag_all",
    "auto_tag_recipe",
    "bind_recipe_to_data",
    "bind_shortlist_to_data",
    "build_catalog",
    "build_index",
    "build_provenance",
    "bundle_provenance",
    "catalog_fingerprint",
    "compose_figure",
    "compute_fully_bound",
    "diff_provenance",
    "discover_data_files",
    "emit_index_json",
    "intake_questions_for_index",
    "load_bindings_cache",
    "load_manifest",
    "load_provenance_json",
    "refine_figure",
    "render_figure_yaml",
    "render_manifest",
    "render_shortlist",
    "resolve_panel_data",
    "run_intake_interactive",
    "scan_project",
    "score_recipes",
    "scoring_rubric_dict",
    "to_intake_pre_filled",
    "to_intake_pre_filled_from_vision",
    "to_render_binding",
    "to_render_data_files",
    "validate_figure_yaml",
    "validate_manifest",
    "validate_tag",
    "validate_tag_dict",
    "verify_provenance",
    "vision_scan_reference_figure",
    "write_bindings_cache",
    "write_catalog_json",
    "write_provenance_json",
    "write_render_report",
]
