"""Manifest schema, resolver, and catalog generator."""

from .auto_tag import auto_tag_all, auto_tag_recipe
from .catalog import (
    INDEX_SCHEMA_VERSION,
    build_catalog,
    build_index,
    catalog_fingerprint,
    emit_index_json,
    write_catalog_json,
)
from .data_bridge import (
    DataFile,
    FieldBinding,
    RecipeBinding,
    bind_recipe_to_data,
    bind_shortlist_to_data,
    compute_fully_bound,
    discover_data_files,
    load_bindings_cache,
    to_render_binding,
    to_render_data_files,
    write_bindings_cache,
)
from .intake import (
    INTAKE_QUESTIONS,
    IntakeAnswer,
    IntakeQuestion,
    intake_questions_for_index,
    run_intake_interactive,
)
from .project_scan import (
    InferredAnswer,
    ProjectScanResult,
    scan_project,
    to_intake_pre_filled,
)
from .render_loop import (
    EnvironmentalFailure,
    RenderBinding,
    RenderDataFile,
    RenderLog,
    RenderOutcome,
    render_shortlist,
    write_render_report,
)
from .resolver import render_manifest, resolve_panel_data, validate_manifest
from .schema import FigureSpec, Manifest, PanelSpec, load_manifest
from .scoring import (
    DEFAULT_SHORTLIST_SIZE,
    MINIMUM_SCORE_FOR_SHORTLIST,
    SCORING_RUBRIC_VERSION,
    WEIGHTS,
    ProjectProfile,
    ScoredRecipe,
    score_recipes,
    scoring_rubric_dict,
)
from .tag_taxonomy import (
    BOOL_TAGS,
    TAG_ENUMS,
    UNKNOWN_SENTINEL,
    TagAnchor,
    TagDimensionality,
    TagDynamics,
    TagValidationError,
    TagWave,
    validate_tag,
    validate_tag_dict,
)

__all__ = [
    "BOOL_TAGS",
    "DEFAULT_SHORTLIST_SIZE",
    "DataFile",
    "EnvironmentalFailure",
    "FieldBinding",
    "FigureSpec",
    "INDEX_SCHEMA_VERSION",
    "INTAKE_QUESTIONS",
    "InferredAnswer",
    "IntakeAnswer",
    "IntakeQuestion",
    "MINIMUM_SCORE_FOR_SHORTLIST",
    "Manifest",
    "PanelSpec",
    "ProjectProfile",
    "ProjectScanResult",
    "RecipeBinding",
    "RenderBinding",
    "RenderDataFile",
    "RenderLog",
    "RenderOutcome",
    "SCORING_RUBRIC_VERSION",
    "ScoredRecipe",
    "TAG_ENUMS",
    "TagAnchor",
    "TagDimensionality",
    "TagDynamics",
    "TagValidationError",
    "TagWave",
    "UNKNOWN_SENTINEL",
    "WEIGHTS",
    "auto_tag_all",
    "auto_tag_recipe",
    "bind_recipe_to_data",
    "bind_shortlist_to_data",
    "build_catalog",
    "build_index",
    "catalog_fingerprint",
    "compute_fully_bound",
    "discover_data_files",
    "emit_index_json",
    "intake_questions_for_index",
    "load_bindings_cache",
    "load_manifest",
    "render_manifest",
    "render_shortlist",
    "resolve_panel_data",
    "run_intake_interactive",
    "scan_project",
    "score_recipes",
    "scoring_rubric_dict",
    "to_intake_pre_filled",
    "to_render_binding",
    "to_render_data_files",
    "validate_manifest",
    "validate_tag",
    "validate_tag_dict",
    "write_bindings_cache",
    "write_catalog_json",
    "write_render_report",
]
