"""Elevation 14 — smart citation insertion from Consensus cache.

E9-phase-1 (``novelty_scout``) already calls the Consensus.app Pro API and
caches the top-paper records per claim/query under
``panelforge_workspace/.consensus_cache/``. E14 closes the loop: it walks
the cache, pairs each cached query with a manuscript claim sentence, and
**suggests ``\\cite{...}`` insertions** at sentence-end positions where
the claim needs literature backing. The module also auto-fills
``references.bib`` with new BibTeX entries derived from the cached papers
— it never modifies existing prose, only appends a citation marker just
before the terminal punctuation of each targeted sentence.

Workflow
--------
1. Parse the manuscript via :func:`manuscript_parse.parse_manuscript` (E10).
2. Walk ``existing.claims`` — every "Figure N shows X" sentence is a
   candidate insertion site.
3. Scan the on-disk Consensus cache via :func:`scan_consensus_cache`.
4. For each claim sentence, find the cached query record whose stored
   ``query`` text has the highest TF-IDF cosine similarity to the claim
   sentence; if it clears ``min_similarity``, emit a
   :class:`CitationSuggestion` for the top-3 papers in that record.
5. ``apply_citation_insertions`` writes the actual ``\\cite{...}`` markers
   in-place (backing up the original) and appends new BibTeX entries to
   ``references.bib`` (also backed up).

Public surface
--------------
* Dataclasses: :class:`CitationSuggestion`, :class:`BibEntry`,
  :class:`CitationInsertionResult`.
* Error: :class:`InserterError`.
* Pure helpers: :func:`scan_consensus_cache`,
  :func:`build_bib_entries_from_consensus`.
* Pipeline: :func:`suggest_citations_for_manuscript`,
  :func:`apply_citation_insertions`.
* Reporter: :func:`render_suggestions_markdown`.
"""

from __future__ import annotations

import json
import math
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

__all__ = [
    "BibEntry",
    "CACHE_DIR_DEFAULT",
    "CitationInsertionResult",
    "CitationSuggestion",
    "InserterError",
    "apply_citation_insertions",
    "build_bib_entries_from_consensus",
    "render_suggestions_markdown",
    "scan_consensus_cache",
    "suggest_citations_for_manuscript",
]

#: Default cache directory (relative to the manuscript's parent).
CACHE_DIR_DEFAULT = "panelforge_workspace/.consensus_cache"


# --------------------------------------------------------------------------- #
# Dataclasses + errors                                                        #
# --------------------------------------------------------------------------- #


class InserterError(RuntimeError):
    """Raised when the inserter cannot proceed (unreadable manuscript,
    write failure, malformed cache layout).
    """


@dataclass(frozen=True)
class CitationSuggestion:
    """One suggested ``\\cite{...}`` insertion.

    Attributes
    ----------
    sentence
        The full claim sentence as it appears in the manuscript (with
        any inline LaTeX commands left verbatim — we do not rewrite the
        prose).
    line_number
        1-indexed line in the manuscript where the sentence terminates.
        Multi-line sentences resolve to their *last* line so the
        in-place writer touches a single line.
    char_offset
        0-indexed column on ``line_number`` at which the citation
        marker should be inserted. The writer inserts
        ``" \\cite{key1,key2}"`` *before* the terminal punctuation
        (so ``"X is true."`` becomes ``"X is true \\cite{...}."``).
    cite_keys
        The BibTeX keys to cite — usually the top-3 papers from the
        matching Consensus query.
    confidence
        TF-IDF cosine similarity between the cached query and the
        claim sentence, clamped to ``[0, 1]``.
    rationale
        Human-readable explanation surfaced in the dry-run report.
    """

    sentence: str
    line_number: int
    char_offset: int
    cite_keys: tuple[str, ...]
    confidence: float
    rationale: str


@dataclass(frozen=True)
class BibEntry:
    """A BibTeX entry derived from a Consensus paper record.

    Attributes
    ----------
    entry_type
        BibTeX entry type — almost always ``"article"`` for Consensus
        hits.
    cite_key
        Canonical ``surnameYEARtopic`` identifier, generated by
        :func:`_generate_cite_key`. Always BibTeX-safe (no spaces,
        punctuation, or Unicode).
    fields
        Field map (``title``, ``author``, ``journal``, ``year``,
        ``doi``, optionally ``url``, ``abstract``). All values
        BibTeX-escaped (braces around capital words, ``\\&`` for
        ampersands).
    """

    entry_type: str
    cite_key: str
    fields: dict[str, str]

    def to_bibtex(self) -> str:
        """Render canonical BibTeX entry.

        Field order is fixed: ``title``, ``author``, ``journal``,
        ``year``, ``doi``, then any remaining fields alphabetically.
        Trailing-comma format so future fields can be appended cleanly.
        """
        ordered_keys = ("title", "author", "journal", "year", "doi")
        emitted: list[str] = []
        seen: set[str] = set()
        for k in ordered_keys:
            if k in self.fields and self.fields[k]:
                emitted.append(f"  {k} = {{{self.fields[k]}}}")
                seen.add(k)
        for k in sorted(self.fields):
            if k in seen:
                continue
            v = self.fields[k]
            if v:
                emitted.append(f"  {k} = {{{v}}}")
        body = ",\n".join(emitted)
        return f"@{self.entry_type}{{{self.cite_key},\n{body}\n}}\n"


@dataclass(frozen=True)
class CitationInsertionResult:
    """Aggregate result of one ``suggest_citations_for_manuscript`` call.

    Holds the dry-run preview (suggestions + bib entries) and the
    on-disk artefacts produced when ``apply_citation_insertions`` is
    chained on top.
    """

    manuscript_path: Path
    n_sentences_scanned: int
    n_suggestions: int
    n_applied: int
    new_bib_entries: tuple[BibEntry, ...]
    suggestions: tuple[CitationSuggestion, ...]
    backup_manuscript_path: Path | None
    backup_bib_path: Path | None


# --------------------------------------------------------------------------- #
# Cache scanning                                                              #
# --------------------------------------------------------------------------- #


def scan_consensus_cache(cache_dir: Path) -> dict[str, list[dict[str, Any]]]:
    """Walk a Consensus cache directory.

    Each ``*.json`` file is read tolerantly:

    * the ``query`` field (if present) keys the result; falls back to
      the file stem otherwise;
    * either ``papers`` or ``top_papers`` (some E9 snapshots use the
      legacy field name) populates the value list;
    * malformed JSON / unreadable files are silently skipped so a
      single corrupt entry doesn't abort the whole scan.

    Returns
    -------
    dict[str, list[dict]]
        Mapping ``query → paper records``. Each record carries the
        Consensus fields (``title``, ``authors``, ``year``,
        ``journal``, ``doi``, ``abstract``, ``relevance_score``) —
        consumers should treat any field as optional.
    """
    if not cache_dir.exists() or not cache_dir.is_dir():
        return {}
    results: dict[str, list[dict[str, Any]]] = {}
    for cache_file in sorted(cache_dir.glob("*.json")):
        try:
            data = json.loads(cache_file.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError, UnicodeDecodeError):
            continue
        if not isinstance(data, dict):
            continue
        query = data.get("query") or cache_file.stem
        papers = data.get("papers") or data.get("top_papers") or []
        if not isinstance(papers, list):
            continue
        valid = [p for p in papers if isinstance(p, dict)]
        if valid:
            results[str(query)] = valid
    return results


# --------------------------------------------------------------------------- #
# BibTeX entry construction                                                   #
# --------------------------------------------------------------------------- #


_STOPWORDS: frozenset[str] = frozenset({
    "a", "an", "and", "as", "at", "be", "by", "for", "from", "has", "in",
    "is", "it", "its", "of", "on", "or", "that", "the", "this", "to",
    "via", "with", "are", "we", "our", "their", "these", "those", "but",
    "if", "into", "than", "when", "where", "which", "while", "who",
    "how", "why", "what", "such",
})

_CITE_KEY_INVALID = re.compile(r"[^a-z0-9]+")
_SURNAME_PUNCT = re.compile(r"[^A-Za-z\-]")


_INITIAL_TOKEN_RE = re.compile(r"^[A-Z](?:\.[A-Z])*\.?$")


def _normalise_surname(author: str) -> str:
    """Extract a single-word surname from a free-form author string.

    Supported author formats:

    * ``"Doe, John"`` — comma-separated surname-first → "doe".
    * ``"Doe J."`` / ``"Doe J"`` — Consensus / Vancouver style
      (surname then initials) → "doe".
    * ``"J. Doe"`` / ``"John A. Doe"`` — Western order (initials
      then surname) → "doe".

    Returns a lowercase BibTeX-safe token (alpha only, hyphens
    preserved). Falls back to ``"anon"`` when the input is unusable.
    """
    if not author:
        return "anon"
    # "Doe, J." → "Doe"
    if "," in author:
        token = author.split(",", 1)[0]
    else:
        tokens = [t for t in author.split() if t]
        if not tokens:
            return "anon"
        # Heuristic: if the LAST token looks like initials (one or
        # more capital letters separated/followed by '.'), assume
        # Consensus / Vancouver order ("Doe J.") and use the FIRST
        # token. Otherwise use the LAST token ("John A. Doe").
        if len(tokens) >= 2 and _INITIAL_TOKEN_RE.match(tokens[-1]):
            token = tokens[0]
        else:
            token = tokens[-1]
    cleaned = _SURNAME_PUNCT.sub("", token).lower()
    return cleaned or "anon"


def _significant_word(title: str) -> str:
    """Pick the first non-stopword token from ``title`` for the cite key.

    Returns lowercase alpha-only; falls back to ``"work"`` when no
    suitable token exists.
    """
    if not title:
        return "work"
    tokens = re.findall(r"[A-Za-z]+", title.lower())
    for tok in tokens:
        if tok not in _STOPWORDS and len(tok) >= 3:
            return tok
    return tokens[0] if tokens else "work"


def _generate_cite_key(
    paper: dict[str, Any],
    *,
    existing_keys: set[str],
) -> str:
    """Generate a unique ``surnameYEARtopic`` cite key.

    Disambiguates collisions by appending ``a``, ``b``, ``c``, ... —
    same convention BibTeX itself uses for same-author-same-year
    duplicates.
    """
    authors = paper.get("authors") or []
    first_author = ""
    if authors:
        first_author = authors[0] if isinstance(authors[0], str) else ""
    surname = _normalise_surname(first_author)

    year = paper.get("year")
    if isinstance(year, int) and year > 0:
        year_str = str(year)
    elif isinstance(year, str):
        m = re.search(r"\d{4}", year)
        year_str = m.group(0) if m else "nd"
    else:
        year_str = "nd"

    topic = _significant_word(paper.get("title", ""))
    base = f"{surname}{year_str}{topic}"
    base = _CITE_KEY_INVALID.sub("", base.lower())
    if not base:
        base = "ref"

    if base not in existing_keys:
        return base
    # Collision: append a, b, c, ...
    for suffix_int in range(26):
        suffix = chr(ord("a") + suffix_int)
        candidate = f"{base}{suffix}"
        if candidate not in existing_keys:
            return candidate
    # Pathological: append a numeric index
    i = 2
    while f"{base}_{i}" in existing_keys:
        i += 1
    return f"{base}_{i}"


def _bibtex_escape(value: str) -> str:
    """Escape a value for safe insertion in a BibTeX ``{ ... }`` field.

    * Strips leading/trailing whitespace and collapses runs of
      whitespace to a single space.
    * Replaces unescaped ``&`` with ``\\&`` (BibTeX expects backslash-
      escapes; raw ``&`` triggers ``unbalanced @`` errors in many
      bibtex flavours).
    * Leaves Unicode intact — modern bibtex / biblatex handle UTF-8.
    """
    if not value:
        return ""
    cleaned = re.sub(r"\s+", " ", str(value)).strip()
    cleaned = re.sub(r"(?<!\\)&", r"\\&", cleaned)
    return cleaned


def _format_authors(authors: list[Any]) -> str:
    """Render an author list in BibTeX ``First Last and First Last`` form.

    Accepts strings (already formatted) or anything ``str()`` can
    coerce. Empty input → empty string (caller drops the field).
    """
    if not authors:
        return ""
    cleaned = [str(a).strip() for a in authors if a]
    return " and ".join(cleaned)


def build_bib_entries_from_consensus(
    papers: list[dict[str, Any]],
    *,
    existing_keys: set[str] | None = None,
) -> tuple[BibEntry, ...]:
    """Convert raw Consensus paper records to :class:`BibEntry` tuples.

    Parameters
    ----------
    papers
        List of paper dicts (as cached by E9). Tolerant of missing
        fields — only ``title`` is treated as load-bearing; everything
        else is filled tolerantly.
    existing_keys
        Cite keys already present in the project's
        ``references.bib``. Newly-generated keys are guaranteed
        unique against this set.

    Returns
    -------
    tuple[BibEntry, ...]
        Entries in input order, with collision-disambiguated keys.
    """
    existing = set(existing_keys or ())
    entries: list[BibEntry] = []
    for paper in papers:
        title = paper.get("title", "").strip()
        if not title:
            # Papers without titles are useless — skip silently.
            continue
        cite_key = _generate_cite_key(paper, existing_keys=existing)
        existing.add(cite_key)

        fields: dict[str, str] = {}
        fields["title"] = _bibtex_escape(title)
        authors = _format_authors(paper.get("authors") or [])
        if authors:
            fields["author"] = _bibtex_escape(authors)
        journal = paper.get("journal", "")
        if journal:
            fields["journal"] = _bibtex_escape(journal)
        year = paper.get("year")
        if isinstance(year, int) and year > 0:
            fields["year"] = str(year)
        elif isinstance(year, str):
            m = re.search(r"\d{4}", year)
            if m:
                fields["year"] = m.group(0)
        doi = paper.get("doi")
        if doi:
            fields["doi"] = _bibtex_escape(str(doi))
        abstract = paper.get("abstract") or paper.get("abstract_excerpt")
        if abstract:
            # Cap abstract length to keep .bib lean; full abstracts
            # bloat the file and stress BibTeX line-length limits.
            short = _bibtex_escape(str(abstract))[:600]
            if short:
                fields["abstract"] = short

        entries.append(
            BibEntry(entry_type="article", cite_key=cite_key, fields=fields)
        )
    return tuple(entries)


# --------------------------------------------------------------------------- #
# Existing-bib parsing (for dedup)                                            #
# --------------------------------------------------------------------------- #


_BIB_KEY_RE = re.compile(
    r"@(?:article|book|inproceedings|incollection|misc|techreport|"
    r"phdthesis|mastersthesis|unpublished|manual|booklet|proceedings|"
    r"online|electronic|software|dataset)\s*\{\s*([^,\s]+)\s*,",
    re.IGNORECASE,
)


def _extract_existing_cite_keys(bib_path: Path) -> set[str]:
    """Parse a ``.bib`` file just enough to collect existing cite keys.

    The parser is deliberately shallow — it only finds the key after
    each ``@entry{`` marker. Returns an empty set when the path does
    not exist or cannot be read.
    """
    if not bib_path.exists() or not bib_path.is_file():
        return set()
    try:
        text = bib_path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return set()
    return {m.group(1).strip() for m in _BIB_KEY_RE.finditer(text)}


# --------------------------------------------------------------------------- #
# TF-IDF similarity (lightweight, no external deps)                           #
# --------------------------------------------------------------------------- #


_WORD_RE = re.compile(r"\b[a-z][a-z]+\b")


def _tokenise(text: str) -> list[str]:
    """Lowercase alphabetic-only tokenizer (matches manuscript_alignment)."""
    return _WORD_RE.findall(text.lower())


def _term_freq(tokens: list[str]) -> dict[str, float]:
    if not tokens:
        return {}
    counts: dict[str, int] = {}
    for t in tokens:
        counts[t] = counts.get(t, 0) + 1
    n = len(tokens)
    return {t: c / n for t, c in counts.items()}


def _doc_freq(docs: list[list[str]]) -> dict[str, int]:
    df: dict[str, int] = {}
    for doc in docs:
        for t in set(doc):
            df[t] = df.get(t, 0) + 1
    return df


def _idf(df: dict[str, int], n_docs: int) -> dict[str, float]:
    return {t: math.log((n_docs + 1) / (c + 1)) + 1.0 for t, c in df.items()}


def _tfidf_vec(tokens: list[str], idf: dict[str, float]) -> dict[str, float]:
    tf = _term_freq(tokens)
    return {t: f * idf.get(t, 1.0) for t, f in tf.items()}


def _cosine(a: dict[str, float], b: dict[str, float]) -> float:
    common = set(a) & set(b)
    if not common:
        return 0.0
    dot = sum(a[t] * b[t] for t in common)
    na = math.sqrt(sum(v * v for v in a.values()))
    nb = math.sqrt(sum(v * v for v in b.values()))
    if na == 0.0 or nb == 0.0:
        return 0.0
    return dot / (na * nb)


def _clamp01(x: float) -> float:
    return min(1.0, max(0.0, x))


# --------------------------------------------------------------------------- #
# Insertion-site detection                                                    #
# --------------------------------------------------------------------------- #


def _existing_cites_in_sentence(sentence: str) -> bool:
    """Return ``True`` if the sentence already contains a ``\\cite``/``[@..]``.

    The inserter refuses to double-cite — if the user has already
    backed the sentence with at least one citation, we leave it
    untouched.
    """
    if re.search(r"\\cite[a-zA-Z]*\s*\{", sentence):
        return True
    return bool(re.search(r"\[(?:-?@[^@\];\]]+)(?:;\s*-?@[^@\];\]]+)*\]", sentence))


def _find_insertion_offset(line: str) -> int:
    """Return the column at which to splice ``\\cite{...}`` into ``line``.

    Prefers the index *just before* the terminal punctuation (so
    ``"X is true."`` becomes ``"X is true \\cite{...}."``). Falls back
    to the end of the rstripped line when no terminal punctuation is
    present.
    """
    rstripped = line.rstrip()
    if not rstripped:
        return len(line)
    last = rstripped[-1]
    if last in ".!?":
        return len(rstripped) - 1
    if last in '"”’\'':
        # Trailing quote — look one char back.
        if len(rstripped) >= 2 and rstripped[-2] in ".!?":
            return len(rstripped) - 2
    return len(rstripped)


# --------------------------------------------------------------------------- #
# End-to-end pipeline                                                         #
# --------------------------------------------------------------------------- #


def _build_idf_for_pair(
    queries: list[str], claims: list[str],
) -> tuple[dict[str, float], dict[str, list[str]]]:
    """Compute a shared IDF across queries + claim sentences.

    Returns ``(idf, tokens_by_doc)`` where ``tokens_by_doc`` maps each
    distinct doc string to its token list (so callers can re-use the
    vector built from the IDF without re-tokenising).
    """
    tokens_by_doc: dict[str, list[str]] = {}
    for s in queries + claims:
        if s not in tokens_by_doc:
            tokens_by_doc[s] = _tokenise(s)
    df = _doc_freq(list(tokens_by_doc.values()))
    idf = _idf(df, max(len(tokens_by_doc), 1))
    return idf, tokens_by_doc


def _best_query_for_claim(
    claim_sentence: str,
    cache: dict[str, list[dict[str, Any]]],
    *,
    idf: dict[str, float],
    tokens_by_doc: dict[str, list[str]],
) -> tuple[str | None, float]:
    """Find the cached query whose text best matches ``claim_sentence``.

    Returns ``(query, similarity)``; ``(None, 0.0)`` when the cache
    is empty.
    """
    if not cache:
        return None, 0.0
    claim_vec = _tfidf_vec(tokens_by_doc[claim_sentence], idf)
    best_query: str | None = None
    best_sim = 0.0
    for query in cache:
        q_vec = _tfidf_vec(tokens_by_doc[query], idf)
        sim = _cosine(claim_vec, q_vec)
        if sim > best_sim:
            best_sim = sim
            best_query = query
    return best_query, _clamp01(best_sim)


def suggest_citations_for_manuscript(
    manuscript_path: Path,
    *,
    cache_dir: Path | None = None,
    min_similarity: float = 0.6,
    existing_bib_path: Path | None = None,
    top_n_papers: int = 3,
) -> CitationInsertionResult:
    """End-to-end dry-run pipeline: scan, match, emit suggestions.

    1. ``parse_manuscript`` → :class:`ExistingManuscript` (E10).
    2. ``scan_consensus_cache`` → ``{query → papers}``.
    3. Compute IDF over (cached queries) ∪ (claim sentences).
    4. For each claim sentence, score against every cached query;
       pick the best match.
    5. Above ``min_similarity``: take the top-N papers, build
       :class:`BibEntry` objects with unique cite keys, emit a
       :class:`CitationSuggestion`.

    Dry-run: nothing is written. ``n_applied == 0`` and both backup
    paths are ``None`` in the returned result.

    Parameters
    ----------
    manuscript_path
        Path to a ``.tex`` or ``.md`` manuscript.
    cache_dir
        Path to the Consensus cache directory. Defaults to
        ``manuscript_path.parent / "panelforge_workspace/.consensus_cache"``.
    min_similarity
        TF-IDF cosine threshold below which a claim sentence is left
        un-cited.
    existing_bib_path
        Optional ``references.bib`` to dedup against. When provided,
        generated cite keys never collide with the existing file.
    top_n_papers
        How many papers from the best-matching cached query to cite.

    Raises
    ------
    InserterError
        On parse failures or unreadable manuscript.
    """
    # Lazy-import the parser so test isolation stays clean.
    from panelforge_figures.manifest.manuscript_parse import (
        ManuscriptParseError,
        parse_manuscript,
    )

    try:
        manuscript = parse_manuscript(manuscript_path)
    except ManuscriptParseError as exc:
        raise InserterError(f"cannot parse manuscript: {exc}") from exc

    cache_path = cache_dir or (manuscript_path.parent / CACHE_DIR_DEFAULT)
    cache = scan_consensus_cache(cache_path)

    existing_keys = _extract_existing_cite_keys(existing_bib_path) if existing_bib_path else set()

    # The claim sentences from E10's parser already classify each
    # sentence that touches a figure. We treat *every* such sentence
    # as a candidate insertion site, deduplicating by (line_number,
    # sentence) so the same sentence containing two figure refs only
    # gets cited once.
    seen_claims: set[tuple[int, str]] = set()
    unique_claims: list[tuple[int, str]] = []
    for c in manuscript.claims:
        key = (c.line_number, c.sentence)
        if key in seen_claims:
            continue
        seen_claims.add(key)
        unique_claims.append(key)

    n_scanned = len(unique_claims)

    # Build shared IDF across cached queries + claim sentences so the
    # cosine similarity is calibrated against the actual corpus.
    queries = list(cache.keys())
    claim_strings = [s for _, s in unique_claims]
    if not queries or not claim_strings:
        return CitationInsertionResult(
            manuscript_path=manuscript_path,
            n_sentences_scanned=n_scanned,
            n_suggestions=0,
            n_applied=0,
            new_bib_entries=(),
            suggestions=(),
            backup_manuscript_path=None,
            backup_bib_path=None,
        )

    idf, tokens_by_doc = _build_idf_for_pair(queries, claim_strings)

    # Re-read the manuscript text so we can resolve sentence-end
    # offsets accurately. (The parser doesn't preserve the raw lines.)
    try:
        raw_text = manuscript_path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        raise InserterError(f"cannot re-read manuscript: {exc}") from exc
    lines = raw_text.splitlines()

    suggestions: list[CitationSuggestion] = []
    new_entries: list[BibEntry] = []
    suggested_keys: set[str] = set(existing_keys)

    for line_no, sentence in unique_claims:
        if _existing_cites_in_sentence(sentence):
            continue

        best_query, sim = _best_query_for_claim(
            sentence, cache, idf=idf, tokens_by_doc=tokens_by_doc,
        )
        if best_query is None or sim < min_similarity:
            continue

        papers = cache[best_query][:top_n_papers]
        new_for_query = build_bib_entries_from_consensus(
            papers, existing_keys=suggested_keys,
        )
        if not new_for_query:
            continue
        for e in new_for_query:
            suggested_keys.add(e.cite_key)
        new_entries.extend(new_for_query)

        # Resolve the insertion offset on the manuscript line.
        idx = line_no - 1
        if 0 <= idx < len(lines):
            offset = _find_insertion_offset(lines[idx])
        else:
            offset = len(sentence)

        rationale = (
            f"matched cached query ‘{best_query}’ "
            f"(cosine {sim:.2f}); top-{len(new_for_query)} papers from cache"
        )
        suggestions.append(
            CitationSuggestion(
                sentence=sentence,
                line_number=line_no,
                char_offset=offset,
                cite_keys=tuple(e.cite_key for e in new_for_query),
                confidence=sim,
                rationale=rationale,
            )
        )

    return CitationInsertionResult(
        manuscript_path=manuscript_path,
        n_sentences_scanned=n_scanned,
        n_suggestions=len(suggestions),
        n_applied=0,
        new_bib_entries=tuple(new_entries),
        suggestions=tuple(suggestions),
        backup_manuscript_path=None,
        backup_bib_path=None,
    )


# --------------------------------------------------------------------------- #
# Apply: actually write to disk                                               #
# --------------------------------------------------------------------------- #


def _backup_path(path: Path) -> Path:
    """Return ``<path>.bak`` (or ``<path>.bak.<n>`` if that exists).

    Never overwrites an existing backup — a fresh backup is created on
    every apply run so the user can roll back to any prior state.
    """
    candidate = path.with_suffix(path.suffix + ".bak")
    if not candidate.exists():
        return candidate
    i = 1
    while True:
        candidate = path.with_suffix(path.suffix + f".bak.{i}")
        if not candidate.exists():
            return candidate
        i += 1


def apply_citation_insertions(
    manuscript_path: Path,
    suggestions: list[CitationSuggestion],
    new_bib_entries: list[BibEntry],
    *,
    existing_bib_path: Path | None = None,
    backup: bool = True,
) -> tuple[Path, Path]:
    """Apply :class:`CitationSuggestion` insertions to disk.

    Behaviour
    ---------
    * Backs up ``manuscript_path`` to ``<path>.bak.tex`` /
      ``<path>.bak.md`` before any edit (when ``backup=True``).
    * Sorts suggestions by ``(line_number desc, char_offset desc)``
      so earlier offsets stay valid as later ones are mutated.
    * Inserts ``" \\cite{key1,key2,...}"`` immediately before the
      terminal punctuation of the targeted sentence.
    * Appends new BibTeX entries to ``existing_bib_path`` (defaults to
      ``manuscript_path.parent / "references.bib"``). Skips entries
      whose cite key already appears in the file.

    Parameters
    ----------
    manuscript_path
        File to mutate.
    suggestions
        From :func:`suggest_citations_for_manuscript`.
    new_bib_entries
        From :func:`suggest_citations_for_manuscript`.
    existing_bib_path
        ``references.bib`` location. Created if missing.
    backup
        When ``False``, edits the manuscript and bib in-place without
        keeping a ``.bak`` copy. Default ``True`` is strongly
        recommended.

    Returns
    -------
    tuple[Path, Path]
        ``(manuscript_path, bib_path)`` for caller convenience.

    Raises
    ------
    InserterError
        On unreadable input, write failure, or invalid line/offset.
    """
    bib_path = existing_bib_path or (manuscript_path.parent / "references.bib")

    # Read manuscript.
    try:
        raw = manuscript_path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        raise InserterError(f"cannot read manuscript: {exc}") from exc

    # Preserve trailing newline if present.
    trailing_newline = raw.endswith("\n")
    lines = raw.splitlines()

    # Backup manuscript before mutating.
    if backup and suggestions:
        try:
            _backup_path(manuscript_path).write_text(raw, encoding="utf-8")
        except OSError as exc:
            raise InserterError(f"cannot back up manuscript: {exc}") from exc

    # Apply edits in reverse order so earlier offsets stay valid.
    sorted_sugs = sorted(
        suggestions,
        key=lambda s: (s.line_number, s.char_offset),
        reverse=True,
    )
    for sug in sorted_sugs:
        idx = sug.line_number - 1
        if not (0 <= idx < len(lines)):
            raise InserterError(
                f"suggestion line {sug.line_number} out of bounds "
                f"(manuscript has {len(lines)} lines)"
            )
        line = lines[idx]
        # Clamp offset to the line length to survive trailing
        # whitespace differences between dry-run and apply.
        offset = max(0, min(sug.char_offset, len(line)))
        if not sug.cite_keys:
            continue
        cite_marker = f" \\cite{{{','.join(sug.cite_keys)}}}"
        lines[idx] = line[:offset] + cite_marker + line[offset:]

    new_text = "\n".join(lines)
    if trailing_newline:
        new_text += "\n"
    try:
        manuscript_path.write_text(new_text, encoding="utf-8")
    except OSError as exc:
        raise InserterError(f"cannot write manuscript: {exc}") from exc

    # Augment references.bib.
    existing_keys = _extract_existing_cite_keys(bib_path)
    fresh_entries = [e for e in new_bib_entries if e.cite_key not in existing_keys]
    if fresh_entries:
        if bib_path.exists():
            try:
                old_bib = bib_path.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError) as exc:
                raise InserterError(f"cannot read existing bib: {exc}") from exc
            if backup:
                try:
                    _backup_path(bib_path).write_text(old_bib, encoding="utf-8")
                except OSError as exc:
                    raise InserterError(f"cannot back up bib: {exc}") from exc
        else:
            old_bib = ""
        sep = "\n" if old_bib and not old_bib.endswith("\n") else ""
        block = "\n".join(e.to_bibtex() for e in fresh_entries)
        if not block.endswith("\n"):
            block += "\n"
        try:
            bib_path.write_text(old_bib + sep + block, encoding="utf-8")
        except OSError as exc:
            raise InserterError(f"cannot write bib: {exc}") from exc

    return manuscript_path, bib_path


# --------------------------------------------------------------------------- #
# Markdown renderer                                                           #
# --------------------------------------------------------------------------- #


def render_suggestions_markdown(result: CitationInsertionResult) -> str:
    """Render a human-readable Markdown report.

    Sections:

    * Headline summary (counts).
    * One block per suggestion (sentence excerpt, cite keys,
      confidence, rationale).
    * BibTeX preview footer listing the keys that would be added.

    Safe to call on an empty result — emits a short "no suggestions"
    note.
    """
    lines: list[str] = []
    lines.append("# Citation Suggestions")
    lines.append("")
    lines.append(f"_Manuscript_: `{result.manuscript_path}`")
    lines.append("")
    lines.append(
        f"_Sentences scanned_: **{result.n_sentences_scanned}**, "
        f"suggestions: **{result.n_suggestions}**, "
        f"applied: **{result.n_applied}**, "
        f"new bib entries: **{len(result.new_bib_entries)}**"
    )
    lines.append("")

    if result.backup_manuscript_path is not None:
        lines.append(f"Backup manuscript: `{result.backup_manuscript_path}`")
    if result.backup_bib_path is not None:
        lines.append(f"Backup bib: `{result.backup_bib_path}`")
    if result.backup_manuscript_path or result.backup_bib_path:
        lines.append("")

    if not result.suggestions:
        lines.append("_No suggestions to apply._")
        lines.append("")
        return "\n".join(lines).rstrip() + "\n"

    lines.append("## Suggestions")
    lines.append("")
    for i, sug in enumerate(result.suggestions, start=1):
        # Truncate very long sentences for readable preview.
        sent_preview = sug.sentence.strip()
        if len(sent_preview) > 200:
            sent_preview = sent_preview[:197] + "..."
        lines.append(f"### {i}. line {sug.line_number}")
        lines.append("")
        lines.append(f"> {sent_preview}")
        lines.append("")
        lines.append(f"- **cite keys**: `{', '.join(sug.cite_keys)}`")
        lines.append(f"- **confidence**: {sug.confidence:.2f}")
        lines.append(f"- **rationale**: {sug.rationale}")
        lines.append("")

    if result.new_bib_entries:
        lines.append("## New BibTeX entries")
        lines.append("")
        lines.append("```bibtex")
        for entry in result.new_bib_entries:
            lines.append(entry.to_bibtex().rstrip())
        lines.append("```")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
